# Generated by Django 4.2.2 on 2023-06-12 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortal', '0002_alter_job_date_posted_alter_job_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 11, 31, 23, 21193, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='due_date',
            field=models.DateField(),
        ),
    ]
